### PR TITLE
Chapter 1 done

### PR DESCRIPTION
**Pull request by urmaul**
### Solutions for Chapter 1

cc vrom911 chshersh

### CODE REVIEW

**Comment by urmaul** [comment]
Hello @vrom911 @chshersh,

I'm a bit confused here. Test suite is failing with errors:

```
src/Chapter1.hs:215: failure in expression `:t 42'
expected: 42 :: Num a => a
 but got: 42 :: Num p => p
                    ^

src/Chapter1.hs:303: failure in expression `1 + 2'
expected: 1 + 2 :: Num a => a
 but got: 3
          ^
```

Although these lines in my commit look exactly like expected ones. What's happening here?

Best regards,
Bogdan

**Comment by vrom911** [comment]
@urmaul Doctest works in a way that it compares the output that you expect (what you wrote after >>> line) with the real received output. In your case, you wrote that you expect `42 :: Num a => a`, but you actually would get `42 :: Num p => p` if you run `:t 42`.

Hope it makes sense now 🙂 

Btw, would you like us to review the PR? I see that you removed our mentions. It is okay in both way 😉

**Comment by urmaul** [comment]
@vrom911, makes sense. Thank you.

>Btw, would you like us to review the PR? I see that you removed our mentions. It is okay in both way 😉

Yes please. This one is simple enough so I didn't want to bother you. And I bothered you anyway :)

**Comment by chshersh** [comment]
> This one is simple enough so I didn't want to bother you. And I bothered you anyway :)

@urmaul No worries at all! In that case, feel free to merge this PR whenever you're happy with it and don't hesitate to ask us to review other chapters, if you want :slightly_smiling_face:

**Pull request merged**
